#!/bin/bash

# AstroNvim Installation Script for Paragonic Plugin
# This installs the plugin for AstroNvim users

echo "=== Installing Paragonic Plugin for AstroNvim ==="

# Get AstroNvim user directory
if [ -n "$XDG_CONFIG_HOME" ]; then
    ASTRONVIM_USER="$XDG_CONFIG_HOME/nvim/lua/user"
elif [ -n "$HOME" ]; then
    ASTRONVIM_USER="$HOME/.config/nvim/lua/user"
else
    echo "❌ Error: Could not determine AstroNvim user directory"
    exit 1
fi

echo "📁 AstroNvim user directory: $ASTRONVIM_USER"

# Check if AstroNvim is installed
if [ ! -d "$ASTRONVIM_USER" ]; then
    echo "📁 AstroNvim user directory not found, creating it..."
    echo "   Creating: $ASTRONVIM_USER"
    
    # Create the user directory structure
    mkdir -p "$ASTRONVIM_USER"
    
    # Create a basic init.lua file for AstroNvim user config
    cat > "$ASTRONVIM_USER/init.lua" << 'EOF'
-- AstroNvim User Configuration
-- This file is automatically generated by paragonic installation

return {
  -- Configure AstroNvim features
  plugins = {
    -- Add your custom plugins here
  },
  
  -- Configure AstroNvim options
  options = {
    -- Add your custom options here
  },
}
EOF
    
    echo "✅ Created AstroNvim user directory and basic configuration"
    echo "📝 Note: You may need to install AstroNvim first:"
    echo "   git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim"
    echo "   nvim --headless -c 'AstroSync' -c 'quit'"
    echo ""
fi

# Create plugins directory if it doesn't exist
PLUGINS_DIR="$ASTRONVIM_USER/plugins"
if [ ! -d "$PLUGINS_DIR" ]; then
    echo "📁 Creating plugins directory: $PLUGINS_DIR"
    mkdir -p "$PLUGINS_DIR"
fi

# Create paragonic plugin configuration
PARAGONIC_PLUGIN="$PLUGINS_DIR/paragonic.lua"
echo "📁 Creating plugin configuration: $PARAGONIC_PLUGIN"

# Get current directory (project path)
PROJECT_PATH=$(pwd)
echo "📁 Project path: $PROJECT_PATH"

# Create the plugin configuration file
cat > "$PARAGONIC_PLUGIN" << EOF
-- Paragonic Plugin Configuration for AstroNvim
-- This file is automatically generated by astronvim_install.sh

return {
  -- Paragonic Plugin for AI Agent Collaboration
  {
    dir = "$PROJECT_PATH",  -- Your project path
    name = "paragonic",
    config = function()
      require('paragonic')
    end,
    lazy = false,  -- Load immediately
    priority = 1000,  -- High priority to load early
    enabled = true,
    -- Optional: Add to AstroNvim's plugin management
    dependencies = {},
    -- Optional: Add to specific file types if needed
    ft = {},
    -- Optional: Add to specific events if needed
    event = {},
  },
}
EOF

echo "✅ Plugin configuration created!"
echo ""
echo "📝 Next steps:"
echo "   1. Restart Neovim or run :AstroSync"
echo "   2. Test the plugin with: :ParagonicAIAgentStart TestAgent"
echo ""
echo "🚀 Available commands:"
echo "   :ParagonicAIAgentStart <agent_name>  - Start AI agent session"
echo "   :ParagonicAIAgentStop                - Stop AI agent session"
echo "   :ParagonicAIAgentStatus              - Show session status"
echo "   :ParagonicAIAgentMessage <message>   - Send AI agent message"
echo "   :ParagonicAIAgentReceive <message>   - Receive Neovim message"
echo "   :ParagonicAIAgentCommand <command>   - Execute Neovim command"
echo "   :ParagonicAIAgentBuffer [id] [start] [end] - Read buffer content"
echo "   :ParagonicAIAgentBufferWrite <id> <line1> <line2> ... - Write buffer content"
echo ""
echo "🧪 To test the installation:"
echo "   nvim -c \"ParagonicAIAgentStart TestAgent\""
echo ""
echo "📁 Plugin configuration: $PARAGONIC_PLUGIN"
echo "📁 Project path: $PROJECT_PATH" 