#!/bin/bash

# Local Installation Script for Paragonic Neovim Plugin
# This installs the plugin directly for local testing

echo "=== Installing Paragonic Plugin Locally ==="

# Get Neovim config directory
if [ -n "$XDG_CONFIG_HOME" ]; then
    NVIM_CONFIG="$XDG_CONFIG_HOME/nvim"
elif [ -n "$HOME" ]; then
    NVIM_CONFIG="$HOME/.config/nvim"
else
    echo "❌ Error: Could not determine Neovim config directory"
    exit 1
fi

# Create Neovim config directory if it doesn't exist
if [ ! -d "$NVIM_CONFIG" ]; then
    echo "📁 Creating Neovim config directory: $NVIM_CONFIG"
    mkdir -p "$NVIM_CONFIG"
fi

# Create plugins directory if it doesn't exist
PLUGINS_DIR="$NVIM_CONFIG/plugins"
if [ ! -d "$PLUGINS_DIR" ]; then
    echo "📁 Creating plugins directory: $PLUGINS_DIR"
    mkdir -p "$PLUGINS_DIR"
fi

# Create paragonic plugin directory
PARAGONIC_DIR="$PLUGINS_DIR/paragonic"
echo "📁 Installing to: $PARAGONIC_DIR"

# Remove existing installation if it exists
if [ -d "$PARAGONIC_DIR" ]; then
    echo "🗑️  Removing existing installation..."
    rm -rf "$PARAGONIC_DIR"
fi

# Create plugin directory
mkdir -p "$PARAGONIC_DIR"

# Copy plugin files
echo "📋 Copying plugin files..."
cp -r lua/ "$PARAGONIC_DIR/"
cp -r test_*.lua "$PARAGONIC_DIR/" 2>/dev/null || true
cp run_integration_test.sh "$PARAGONIC_DIR/" 2>/dev/null || true

# Create plugin info file
cat > "$PARAGONIC_DIR/plugin/paragonic.vim" << 'EOF'
" Paragonic Plugin - AI Agent Collaboration for Neovim
" This file is automatically generated by install_local.sh

" Plugin metadata
let g:paragonic_version = "0.1.0"
let g:paragonic_loaded = 1

" Load the main plugin
lua require('paragonic')
EOF

# Create plugin directory structure
mkdir -p "$PARAGONIC_DIR/plugin"

echo "✅ Installation complete!"
echo ""
echo "📝 To use the plugin, add this to your Neovim config:"
echo "   (usually ~/.config/nvim/init.lua or ~/.config/nvim/init.vim)"
echo ""
echo "   -- For Lua config (init.lua):"
echo "   require('paragonic')"
echo ""
echo "   -- For Vim config (init.vim):"
echo "   lua require('paragonic')"
echo ""
echo "🚀 Available commands:"
echo "   :ParagonicAIAgentStart <agent_name>  - Start AI agent session"
echo "   :ParagonicAIAgentStop                - Stop AI agent session"
echo "   :ParagonicAIAgentStatus              - Show session status"
echo "   :ParagonicAIAgentMessage <message>   - Send AI agent message"
echo "   :ParagonicAIAgentReceive <message>   - Receive Neovim message"
echo "   :ParagonicAIAgentCommand <command>   - Execute Neovim command"
echo "   :ParagonicAIAgentBuffer [id] [start] [end] - Read buffer content"
echo "   :ParagonicAIAgentBufferWrite <id> <line1> <line2> ... - Write buffer content"
echo ""
echo "🧪 To test the installation:"
echo "   nvim -c \"lua require('paragonic')\" -c \"ParagonicAIAgentStart TestAgent\""
echo ""
echo "📁 Plugin installed at: $PARAGONIC_DIR" 