-- Migration: Add pattern executions table
-- Created: 2025-08-08

-- Create pattern_executions table
CREATE TABLE pattern_executions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pattern_id UUID NOT NULL REFERENCES system_patterns(id) ON DELETE CASCADE,
    session_id UUID,
    execution_status VARCHAR(50) NOT NULL,
    input_data JSONB,
    output_data JSONB,
    error_message TEXT,
    execution_time_ms INTEGER,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_pattern_executions_pattern_id ON pattern_executions(pattern_id);
CREATE INDEX idx_pattern_executions_session_id ON pattern_executions(session_id);
CREATE INDEX idx_pattern_executions_execution_status ON pattern_executions(execution_status);
CREATE INDEX idx_pattern_executions_started_at ON pattern_executions(started_at);
CREATE INDEX idx_pattern_executions_created_at ON pattern_executions(created_at);

-- Add comments for documentation
COMMENT ON TABLE pattern_executions IS 'Tracks the execution history of system patterns';
COMMENT ON COLUMN pattern_executions.pattern_id IS 'Reference to the system pattern that was executed';
COMMENT ON COLUMN pattern_executions.session_id IS 'Optional session identifier where the pattern was executed';
COMMENT ON COLUMN pattern_executions.execution_status IS 'Status of the execution (e.g., running, completed, failed)';
COMMENT ON COLUMN pattern_executions.input_data IS 'Input data provided to the pattern execution';
COMMENT ON COLUMN pattern_executions.output_data IS 'Output data generated by the pattern execution';
COMMENT ON COLUMN pattern_executions.error_message IS 'Error message if the execution failed';
COMMENT ON COLUMN pattern_executions.execution_time_ms IS 'Execution time in milliseconds';
COMMENT ON COLUMN pattern_executions.started_at IS 'When the execution started';
COMMENT ON COLUMN pattern_executions.completed_at IS 'When the execution completed (null if still running)';
